const STORE_KEY = `git`;

export const LOGIN = `${STORE_KEY}/LOGIN`;
export const LOGIN_SUCCESS = `${STORE_KEY}/LOGIN_SUCCESS`;
export const LOGIN_FAILURE = `${STORE_KEY}/LOGIN_FAILURE`;
export const GET_USER = `${STORE_KEY}/GET_USER`;
export const GET_USER_SUCCESS = `${STORE_KEY}/GET_USER_SUCCESS`;
export const GET_USER_FAILURE = `${STORE_KEY}/GET_USER_FAILURE`;
export const GET_FOLLOWERS = `${STORE_KEY}/GET_FOLLOWERS`;
export const GET_FOLLOWERS_SUCCESS = `${STORE_KEY}/GET_FOLLOWERS_SUCCESS`;
export const GET_FOLLOWERS_FAILURE = `${STORE_KEY}/GET_FOLLOWERS_FAILURE`;
