const STORE_KEY = `catalog`;

export const SEARCH_SHOW = `${STORE_KEY}/SEARCH_SHOW`;
export const SEARCH_SHOW_SUCCESS = `${STORE_KEY}/SEARCH_SHOW_SUCCESS`;
export const SEARCH_SHOW_FAILURE = `${STORE_KEY}/SEARCH_SHOW_FAILURE`;
