const STORE_KEY = `catalog`;

export const SEARCH_SHOW = `${STORE_KEY}/SEARCH_SHOW`;
export const SEARCH_SHOW_SUCCESS = `${STORE_KEY}/SEARCH_SHOW_SUCCESS`;
export const SEARCH_SHOW_FAILURE = `${STORE_KEY}/SEARCH_SHOW_FAILURE`;
export const GET_ACTORS = `${STORE_KEY}/GET_ACTORS`;
export const GET_ACTORS_SUCCESS = `${STORE_KEY}/GET_ACTORS_SUCCESS`;
export const GET_ACTORS_FAILURE = `${STORE_KEY}/GET_ACTORS_FAILURE`;
